# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  jupyter:
    build: .
    volumes:
      - ./:/home
    ports:
      - 8888:8888
    working_dir: /home

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
